### ISSUE TITLE
TESTE DE CAIXA PRETA

### ISSUE THREAD

**Issue by LucasCiocari** [s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos#1]
[METODO DE TESTE CAIXA PRETA UTILIZANDO EQUIVALENCIA PAIR-WISE.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2443577/METODO.DE.TESTE.CAIXA.PRETA.UTILIZANDO.EQUIVALENCIA.PAIR-WISE.zip)

**Comment by LucasCiocari** [comment]
[METODO DE TESTE CAIXA PRETA UTILIZANDO EQUIVALENCIA PAIR-WISE.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447777/METODO.DE.TESTE.CAIXA.PRETA.UTILIZANDO.EQUIVALENCIA.PAIR-WISE.zip)

**Comment by fabianoseller** [comment]
![screenshot_26](https://user-images.githubusercontent.com/42979563/46497294-8c9d5600-c7f0-11e8-8479-881815f0708e.jpg)

**Comment by LucasCiocari** [comment]
[dados.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2451952/dados.zip)
