### ISSUE TITLE
Teste case 003 e 004

### ISSUE THREAD

**Issue by LucasCiocari** [s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos#2]

**Comment by LucasCiocari** [comment]
[test_case_003.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447667/test_case_003.zip)

**Comment by fabianoseller** [comment]
Caso de teste.
[Test-case004.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447672/Test-case004.zip)

**Comment by LucasCiocari** [comment]
[test_case_004_validado.zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447696/test_case_004_validado.zip)

TESTE EXECUTADO

**Comment by fabianoseller** [comment]
[Test-case-validado_003.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447706/Test-case-validado_003.pdf)

TESTE EXECUTADO.

**Comment by fabianoseller** [comment]
[Teste Case Validado003 .zip](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/Teste_Juros_Compostos/files/2447718/Teste.Case.Validado003.zip)

Adicionado teste_case 003
